// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    identity
    (
        init => init
        upgrade => upgrade
        getPersona => get_persona
        getPersonaByAddress => get_persona_by_linked_wallet
        addWallet => add_wallet
        removeWallet => remove_wallet
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
